name: "Messages are not making it through the bridge"
description: "As a Matrix or IRC user, my messages don't seem to make it through"
title: "Messages are not making it through the bridge"
labels: ["support", "I-MissingMessages"]

body:
  - type: dropdown
    id: errortype
    attributes:
      label: Error type
      description: What type of error do you see?
      options:
        - Matrix -> IRC doesn't work
        - IRC -> Matrix doesn't work
        - None work
  - type: checkboxes
    id: statuscheck
    attributes:
      label: Status Check
      description: Please check on https://status.matrix.org that the team is not already aware of the issue
      options:
        - label: I checked https://status.matrix.org
          required: true
  - type: input
    id: federationcheck
    attributes:
      label: Federation Check
      description: Please check on https://federationtester.matrix.org that your server federates correctly and paste your server domain here
      placeholder: example.com
    validations:
      required: true
  - type: input
    id: matrixid
    attributes:
      label: Your Matrix ID, if you're a Matrix user
      description: Your Matrix ID helps us finding issues related to you in the logs
      placeholder: "@username:example.com"
    validations:
      required: false
  - type: input
    id: room
    attributes:
      label: Room/channel affected
      description: What is the room affected by the issue?
      placeholder: #myroom:example.com or #myroom
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Time of the issue
      description: When did the issue occur, in UTC time?
      placeholder: 15:34 UTC
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
