name: "There is spam in a room I manage"
description: "I’m an IRC op and there is spam coming from Matrix to my IRC channel."
title: "There is spam in a room I manage"
labels: ["spam"]

body:
  - type: markdown
    attributes:
      value: | 
          Please report spam to abuse@matrix.org and don't open issues on this repository.
  - type: checkboxes
    id: reporting
    attributes:
      label: Reporting Spam
      description: Spam reports must go through abuse@matrix.org
      options:
        - label: I'm going to report spam to abuse@matrix.org
